// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWKAb7tz4qgl0W6m_UL2GbhDAVT5bstk',
    appId: '1:541959829571:web:6857b404b906f45ca47cf6',
    messagingSenderId: '541959829571',
    projectId: 'hexagon-cup-59863',
    authDomain: 'hexagon-cup-59863.firebaseapp.com',
    storageBucket: 'hexagon-cup-59863.firebasestorage.app',
    measurementId: 'G-MPXZJ13RTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqHSPvVRheGzuwV_8A530RtPVPMvD6wo',
    appId: '1:541959829571:android:fc15fc497ac63af2a47cf6',
    messagingSenderId: '541959829571',
    projectId: 'hexagon-cup-59863',
    storageBucket: 'hexagon-cup-59863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYHNUc_9BXeGbAfSzRO6shb6hhpFy-E88',
    appId: '1:541959829571:ios:56ce6b4d7810e197a47cf6',
    messagingSenderId: '541959829571',
    projectId: 'hexagon-cup-59863',
    storageBucket: 'hexagon-cup-59863.firebasestorage.app',
    iosBundleId: 'com.hexagon.admissaoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLWKAb7tz4qgl0W6m_UL2GbhDAVT5bstk',
    appId: '1:541959829571:web:648d458911b5ea70a47cf6',
    messagingSenderId: '541959829571',
    projectId: 'hexagon-cup-59863',
    authDomain: 'hexagon-cup-59863.firebaseapp.com',
    storageBucket: 'hexagon-cup-59863.firebasestorage.app',
    measurementId: 'G-F7412SDJX2',
  );
}
